### ISSUE TITLE
Support to pass envvars in the exec sdk

### ISSUE THREAD

**Issue by pchico83** [docker/extensions-sdk#124]
My extension is using the exec SDK. it would be useful to pass environment variables to the command execution. This is useful, for example, to track the origin of the command execution. Otherwise, we are force to use command flags, but envars are a cleaner approach in this case.

**Comment by gtardif** [comment]
Added in our backlog (with #130)

**Comment by felipecruz91** [comment]
It is now possible to change the current working directory and provide environment variables when executing commands on the VM or on the host.

```typescript
ddClient.extension.vm.cli.exec('ls', ['-als'], { cwd: '/path/in/container', env: {'FOO': 'foo'} });
ddClient.extension.host.cli.exec('kubectl', [], { cwd: '/path/in/host', env: { 'SOME_K8S_ENV_VAR': 'value' }});
ddClient.docker.cli.exec('compose' ['up', '--rm'], { cwd: '/path/in/host', env: { 'FOO': 'foo'}}
```

@benja-M-1 We need to add these examples to the documentation.

**Comment by benja-M-1** [comment]
I created a ticket for that :)
