### ISSUE TITLE
Ability to provide working directory for exec commands

### ISSUE THREAD

**Issue by mikesir87** [docker/extensions-sdk#130]
## Elevator Pitch

When performing exec commands (such as a `docker compose up` or `docker build`), it would be nice to provide the working directory the commands should run in, rather than having to rely on additional arguments in the command. This capability would let interactive guides 1) use simpler commands in guides and 2) execute the same command in the guide.

## Workarounds

We've currently been working around this by trying two different methods...

1. The guide indicates the simpler command `docker compose up`, but the actual executed command runs `docker compose -f /path/to/docker-compose.yml up`. While this works, it means we have to either maintain two different commands in writeups or automatically inject the `-f` flag (which can be brittle).
2. The guide provides the full command of `docker compose -f /path/to/docker-compose.yml up`. While this would allow a user to simply copy/paste it into their command line without having to change their directory, the command is certainly more complicated.

## Proposal

My proposal would be to add an additional option to the options allowed with the `exec` command. The idea is to combine this with the new modal dialog command to allow a user to select the directory they want to work in. We'd store that value, potentially create files (#129), and then execute commands in that working directory.

```javascript
const result = await ddClient.docker.cli.exec("compose", [ "up" ], { workingDirectory: "/path/to" });
```

**Comment by benja-M-1** [comment]
related to #124 
As the SDK relies on node `process.exec` and `process.spawn` functions the cwd and env options could be exposed.

**Comment by gtardif** [comment]
Added in our backlog (with #124)

**Comment by felipecruz91** [comment]
It is now possible to change the current working directory and provide environment variables when executing commands on the VM or on the host.

```typescript
ddClient.extension.vm.cli.exec('ls', ['-als'], { cwd: '/path/in/container', env: {'FOO': 'foo'} });
ddClient.extension.host.cli.exec('kubectl', [], { cwd: '/path/in/host', env: { 'SOME_K8S_ENV_VAR': 'value' }});
ddClient.docker.cli.exec('compose' ['up', '--rm'], { cwd: '/path/in/host', env: { 'FOO': 'foo'}}
```
