### ISSUE TITLE
Issue with npm dependency when running docker extension init

### ISSUE THREAD

**Issue by dominicholt** [docker/extensions-sdk#146]
When running docker extension init <repo/name> it doesn't appear to matter what is typed in to the Extension SDK version (I'm typing 0.2.3), the following error happens:

npm ERR! Invalid tag name "^": Tags may not have any characters that encodeURIComponent encodes.

This is because in the "ui" folder of the generated project the package.json has a dependency under both "dependencies" and "devDependencies" that is incorrectly missing the correct tag info from the prompt:
 "@docker/extension-api-client-types": "^"

**Comment by gtardif** [comment]
>Resolved with SDK version 0.2.4

Thanks!
