### ISSUE TITLE
Minimal backend sample needs minor repairs

### ISSUE THREAD

**Issue by aerabi** [docker/extensions-sdk#154]
I was following the [minimal backend extension](https://github.com/docker/extensions-sdk/blob/main/docs/tutorials/minimal-backend-extension.md) tutorial and a few things didn't work along the way:
- More labels were required on the Docker image, so I have to add the following:
    + `com.docker.extension.screenshots`
    + `com.docker.extension.detailed-description`
    + `com.docker.extension.publisher-url`
    + `com.docker.extension.additional-urls`
    + `com.docker.extension.changelog`
- The logo was required on the `metadata.json`
- Installation failed because it expected the logo to be local (on the Docker image)

I can change the sample and the tutorial accordingly to include the mentioned points, if approved.

**Comment by benja-M-1** [comment]
Hi @aerabi 👋 thank you for the feedback! PR are always welcome, feel free to propose the changes 😄

**Comment by aerabi** [comment]
Hi @benja-M-1! :wave:

Thanks for the kind response. :blush:  The PR is here.

**Comment by benja-M-1** [comment]
Closed by #179
