### ISSUE TITLE
Uninstalling Extensions sometimes fails

### ISSUE THREAD

**Issue by ingshtrom** [docker/extensions-sdk#161]
When uninstalling Docker extensions, sometimes there is an ambiguous error. The extension seems to be removed properly, but the error makes me think maybe there is an underlying piece that wasn't uninstalled correctly. I also don't think this is specific to the logs explorer extension, but maybe it is.

![image](https://user-images.githubusercontent.com/571756/167683013-ca16fd0d-706e-427f-b505-528c4e57abee.png)

Information about the version of Docker Desktop for Mac that I am using:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/571756/167683138-a26084d1-af7c-4f27-aa05-2500cfaa7697.png">

**Comment by gtardif** [comment]
thx @ingshtrom , this is likely a corner case we are fixing (sometimes the image might have been removed in the meantime by a `docker prune` or `rmi` , if the extension has no backend side, the image is not used at runtime by the extension. )

**Comment by gtardif** [comment]
Fixed and shipped with Desktop 4.9
