### ISSUE TITLE
Docker Extension Containers are not restarted properly

### ISSUE THREAD

**Issue by ingshtrom** [docker/extensions-sdk#162]
I stopped a container that was running one of the extensions' backend. I expected that when I went back to the extension, it would start the container, but it didn’t. There were infinite loading icons for both of the extensions I tried (Trivy and Anchore). I think the SDK should handle ensuring the backend container is up since I don't think the extension has the ability to ensure that the backend is running, right? Here is a video showing what I am talking about.

https://user-images.githubusercontent.com/571756/167684599-78f81468-0845-4681-8402-e66159f74546.mp4

Here is the Docker Desktop for Mac version I am running:
![image](https://user-images.githubusercontent.com/571756/167684660-17cd47dd-1635-4ce4-a7d5-76c4710afcdc.png)

**Comment by benja-M-1** [comment]
@ingshtrom this has been fixed in 4.9, the extension's container are restarted whenever the extension tab is cliked

**Comment by bidzhao** [comment]
This fix impacts my case. I have some one-time containers to do initialization jobs . After initialization is done, the containers go to exited state as expected. But the extension SDK keeps restarting them to be running again, even if when I set 'restart: "no"' for those containers in docker compose file. I hope SDK can provide a way to users that users can decide which container could be not automatically restarted,  by overriding it in either docker compose file or metadata.json is fine.

**Comment by bidzhao** [comment]
BTW, containers started for the first when installing extension or it is brought up by desktop startup, the container is being auto-restarted by SDK when it is in exited state, even if it has 'restart: "no"' in compose file. I hope this can be disabled too.
