### ISSUE TITLE
After initializing an extension, running "make extension" fails

### ISSUE THREAD

**Issue by dominicholt** [docker/extensions-sdk#164]
When running the command "make extension", the output is the following:

make: Nothing to be done for `extension'.

Just running "make" produces this result:
Building...
CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o bin/service ./vm

However, if I run "docker extension ls" afterward, the extension is not listed.

I'm running the ARM version of the Extensions SDK on an M1 Mac.

**Comment by felipecruz91** [comment]
Hi @dominicholt, can you try running `make build-extension` instead?

**Comment by dominicholt** [comment]
This works, thank you. Would suggest updating instructions here: https://docker-desktop-extensions.netlify.app/tutorials/initialize/#opening-dev-tools

**Comment by felipecruz91** [comment]
The documentation has been updated accordingly and moved to https://docs.docker.com/desktop/extensions-sdk
