### ISSUE TITLE
cli: ux: add ability to select frontend language during initialization (JavaScript vs TypeScript)

### ISSUE THREAD

**Issue by Dentrax** [docker/extensions-sdk#171]
It would be nice to add a support to decide which language we want to go with. For example, [react-extension](https://github.com/docker/extensions-sdk/tree/main/samples/react-extension) is built using TypeScript whereas [vm-ui](https://github.com/docker/extensions-sdk/tree/main/samples/vm-ui-plugin/client/src) boilerplate uses JavaScript instead.

Adding a new `--frontend-lang <js|ts>` flag would be great.

**Comment by gtardif** [comment]
Thx for the feedback. 
Likely we'll align our samples and code generated with `docker extension init` to use Typescript everywhere

**Comment by benja-M-1** [comment]
The boilerplate provided by the CLI has been updated to generate a typescript React app.
