### ISSUE TITLE
Unable to initialize new extension from MinGW

### ISSUE THREAD

**Issue by slecache** [docker/extensions-sdk#176]
I installed Docker Desktop Extensions CLI for Windows and it works well:
```
$ docker extension ls
ID                               PROVIDER            VERSION             UI                     VM                  HOST
docker/disk-usage-extension      Docker Inc.         0.2.3               1 tab(Disk usage)      -                   -
docker/logs-explorer-extension   Docker Inc.         0.1.4               1 tab(Logs Explorer)   -                   -
`` `
But, I got this error when I try to `docker extension init myproject` from MinGW (Git Bash):
```
? Hub repository (eg. namespace/repository on hub): Fonction incorrecte.
```

FYI, it works well from PowerShell and WSL2 (Ubuntu).

**Comment by gtardif** [comment]
Thx for the feedback, we'll investigate this terminal specific issue

**Comment by felipecruz91** [comment]
The Extensions CLI uses the [go-survey](https://github.com/go-survey/survey/) library that currently has that limitation:

- https://github.com/go-survey/survey/issues/148

The workaround for this is to create a temporary or permanent alias (in the `~/.bashrc`, for instance):

`alias docker='winpty -Xallow-non-tty docker'`

After that, you can create an extension successfully:

<img width="1062" alt="Screenshot 2022-12-09 at 10 44 17" src="https://user-images.githubusercontent.com/15997951/206673182-e655243b-3665-4a93-ac06-f8f0db771306.png">

**Comment by felipecruz91** [comment]
Closing issue as it's something we cannot fix on our side until a resolution for https://github.com/go-survey/survey/issues/148 is provided.
