### ISSUE TITLE
NavigationIntents methods not working?

### ISSUE THREAD

**Issue by johnharris85** [docker/extensions-sdk#182]
SDK version: 0.2.3

I'm trying to use `await ddClient.desktopUI.navigate.viewContainer(id)` and getting `Error: Error invoking remote method 'navigate-to-container': Error: not found`. I am using `navigate` as when I use the documented `navigation` it errors saying that method doesn't exist on `desktopUI`.

**Comment by felipecruz91** [comment]
Thank you @johnharris85 for reporting the issue. This is indeed a typo in our documentation and we'll be fixing this soon.

As you pointed out, the correct property name to use is `navigate`, e.g:

```typescript
const viewContainer = async () => {
    await ddClient.desktopUI.navigate.viewContainer(
      "72934ea5bc8542abbbe1573a30d9024004245fd5d8f2de524e715edc3a0be900"
    );
  };
```
