### ISSUE TITLE
docker-desktop:// protocol not consistently opening / working on Linux

### ISSUE THREAD

**Issue by johnharris85** [docker/extensions-sdk#183]
Only tested on Linux w/Chrome, but the `docker-desktop://dashboard/open` custom link handler doesn't appear to work all the time. Sometimes it doesn't do anything, sometimes it asks to open an external app then doesn't do anything. Once (when clicking the link from slack) it opened correctly and forwarded me to DD. 

If I run manually in the terminal:
```
 $ xdg-open docker-desktop://dashboard/open
 + curl -X POST --unix-socket /home/john/.docker/desktop/backend.sock http://localhost/registry/complete-login -H Content-Type: application/json -d {"url": "docker-desktop://dashboard/open"}
```
Then if I run that curl command, DD opens and I get an error:
```
Login failed
(b821d87b) d21eca23-BackendAPI S<-C curl/7.68.0 binding: code=415, message=Unsupported Media Type
```
If I click 'Try Again' on that error dialog I get a browser opened at `https://hub.docker.com/auth/desktop/redirect?code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&state=zzzzzzzzzzzz`. Then I hit 'Proceed to Docker Desktop' and nothing happens. It's trying to open `docker-desktop://auth0/complete-login?code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&state=zzzzzzzzzzzz` and Chrome dev logs shows `Launched external handler for 'docker-desktop://auth0/complete-login?code=xxxxxxxxxxxxx&state=zzzzzzzzzzzz'.` but never opens anything.

**Comment by felipecruz91** [comment]
Thank you @johnharris85 for reporting the issue.

We have added to our internal backlog and we'll let you know once it's fixed.

**Comment by johnharris85** [comment]
I installed 4.9 today and saw the following error while installing (possibly related to this issue?):

`Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)`

:man_shrugging:

**Comment by felipecruz91** [comment]
Hi @johnharris85, is this issue still happening in the latest version of Docker Desktop? (4.15)

**Comment by RyzeNGrind** [comment]
Hello I am unsure if this is the correct issue to post in, but I am experiencing similar system handler redirection issues on Windows 10 Docker Desktop. 
No matter how many times I click sign in...
![image](https://github.com/docker/extensions-sdk/assets/14363544/f21fb820-6e4c-42ab-b593-ebb17d0b0d2f)
I am unable to get the redirect link to work.
It gives me a (link)[https://hub.docker.com/auth/desktop/redirect?code=054eGg0GFdJ_8M6MiTOY7lEWzGuknxZpDQxyTihchNppc&state=CFfUFrj4Wg5-S8NIQqVEUzC9SoTXbC57BLMoym03J8Q]
![image](https://github.com/docker/extensions-sdk/assets/14363544/fb5ed772-9aa0-42fd-b92c-44061ae7d88d)
Which seems to be completely broken.

I have already logged in with `docker login` in the CLI but it doesn't seem to fix the issue at hand. Kindly advise.

**Comment by benja-M-1** [comment]
Hi @RyzeNGrind I think your issue should be reported to https://github.com/docker/for-win instead. It seems not related to the Docker extension per see.

Would you mind opening an issue there instead? 
Thank you very much.
