### ISSUE TITLE
NavigationIntents not working

### ISSUE THREAD

**Issue by johnharris85** [docker/extensions-sdk#186]
https://github.com/docker/extensions-sdk/issues/182 was closed prematurely and I can't re-open, so new issue :)

There was an issue with docs (now fixed), however using `await ddClient.desktopUI.navigate.viewContainer(id)` doesn't work either, I get the error in devtools -> `Error: Error invoking remote method 'navigate-to-container': Error: not found`.

I noticed that this repo is on release 0.2.4, but npm is on 0.2.3, is there perhaps some mismatch? Or something didn't get pushed to npm properly?

**Comment by felipecruz91** [comment]
Hi @johnharris85, are you using the full container id as per the [documentation](https://docs.docker.com/desktop/extensions-sdk/dev/api/dashboard-routes-navigation/)?

The full container id, e.g. 46b57e400d801762e9e115734bf902a2450d89669d85881058a46136520aca28. You can use the --no-trunc flag as part of the docker ps command to display the full container id.

**Comment by benja-M-1** [comment]
Hi @johnharris85 do you still have the issue?
Can you share with us a reproduction?
Thank you 🙏

**Comment by felipecruz91** [comment]
@benja-M-1 I had a meeting with @johnharris85 and IIRC the issue was that he programmatically created a container and when trying to navigate to it, the container was not created yet. I think the workaround was to "sleep" a few milliseconds just before navigating to it.

**Comment by johnharris85** [comment]
Yep was a race condition as @felipecruz91 says above. I guess the programmatic creation case will be a fairly common one? So maybe a note in the docs around this, or an auto-retry built into some of the backend calls?

**Comment by benja-M-1** [comment]
Alright, you could use docker events as well for this kind of use cases, listen for containers creation events.

Anyway, I changed the labels, maybe adding this kind of feature in the examples may make sens. cc @gtardif

**Comment by gtardif** [comment]
We have now included a retry in the SDK (with Docker Desktop 4.12, release last week) , so that should avoid race condition when navigating to a container that has just been created. Please feel free to re-open if you still encounter the issue
