### ISSUE TITLE
Can't see Extensions on 4.9.0

### ISSUE THREAD

**Issue by SergioSuarezDev** [docker/extensions-sdk#193]
Extensions are not working now on 4.9.0 (80466) MacOS?
MacOS Version is: 14.4

Can't see the option on this version:
<img width="1262" alt="171995530-ffe58666-fadb-4087-a1cf-f2fb1c6e5397" src="https://user-images.githubusercontent.com/3636232/172121714-7d12315f-e03d-4186-9a05-ab97fa0afbc9.png">

**Comment by SergioSuarezDev** [comment]
I am trying to generate the diagnostic but I also get this error:
**Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': [object Object]**

**Comment by SergioSuarezDev** [comment]
```
▶ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics
```

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

On the other hand, I don't know if it has something to do with it, but after deactivating kubernetes and restarting docker it seems that the extensions are back again.

**Comment by felipecruz91** [comment]
Thank you @SergioSuarezDev. We'll start investigating if having Kubernetes enabled could have some undesired side-effects on Desktop Extensions. 

Not sure why the generation of diagnostics failed. If you could try again at some point today, it'd be very much helpful for us.

**Comment by benja-M-1** [comment]
Hi @SergioSuarezDev, so you know a first "fix" has been released in docker desktop 4.9.1. The bug might still appear so I keep the issue open for now for our tracking purpose.

**Comment by gtardif** [comment]
Apparently we still have issues with this symptom happening randomly. The workaround for now is still to just restart the Dashboard. 
We should have a better fix for it shipped with the next version of Docker Desktop (4.11)

**Comment by gtardif** [comment]
This should have been fixed now, please re-open this issue if you still encounter symptoms with Docker Desktop 4.12 (released last week)
