### ISSUE TITLE
MUI in docker extension is broken

### ISSUE THREAD

**Issue by tukobadnyanoba** [docker/extensions-sdk#204]
**Describe the bug**
I am using below in my code 
`<TextField id="outlined-basic" label="Outlined" variant="outlined" />`
It doesn't render the component properly as it gets rendered properly with normal react-js project.

I created a plain react-js project and added mui in it, it works as expected. It looks like below.
![Screenshot_2022-07-05_18-48-07](https://user-images.githubusercontent.com/103058726/177337181-5e4299f2-cf3f-49b8-ba25-a79d8b327068.png)

So, issue is just with mui in docker extension sdk. 
**Add the steps to reproduce**
1. Create a new extension project with `docker extension` cli
2. Add TextField and observe the output. It will render something like below which isn't correct.
![Screenshot_2022-07-05_18-47-52](https://user-images.githubusercontent.com/103058726/177337288-42b7467a-221e-47fb-a670-5a5f288140ec.png)

**Describe the expected behavior**
All the components from MUI with default css should be properly rendered.
**Optional: Add screenshots**

**Output of `docker extension version`:**

```
Client Version: v0.2.4
Server API Version: 0.2.3
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: v1.0.25
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.9.0 (80466)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Include the Diagnostics ID**

```
(paste your output here)
```

**Additional context**

**Comment by felipecruz91** [comment]
Hi @tukobadnyanoba, could you check that you're using the latest version of the [docker-mui-theme](https://www.npmjs.com/package/@docker/docker-mui-theme) package? (`0.0.7`) as of today.
