### ISSUE TITLE
Create buttons to link to extension with parameters

### ISSUE THREAD

**Issue by benja-M-1** [docker/extensions-sdk#206]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example. 'I'm always frustrated when [...]'

I wish I can add buttons on github or in my product to open my extension and trigger some actions in it.

**Describe the solution you'd like**

Given I created an extension for my company which does specific actions:
* go on my team's GitHub page
* click on "Start on Acme Inc. Docker Extension"
* it opens Docker Desktop
* it starts acme/our-extension with `project=foo&action=bar` as query parameters
* the extension start action "bar" on the project "foo".

**Describe alternatives you've considered**

So far, none as it is not possible to do things like that.

**Additional context**

Maybe @kameshsampath could describe a concrete idea with Drone?

**Comment by kameshsampath** [comment]
@benja-M-1  thanks for opening this issues.  I have added the details  of what is expected out this feature via https://github.com/harness/drone-desktop-docker-extension/issues/3.

**Comment by gtardif** [comment]
Hi @kameshsampath, in recent releases of Desktop, we added the ability to open an extension from a link, and pass query parameters to it. 
You can use URLs of the form: https://open.docker.com/dashboard/extension-tab?extensionId=myorg/my-extension&token=xxx
