### ISSUE TITLE
Can't see unpublished extensions in "Installed" tab

### ISSUE THREAD

**Issue by benja-M-1** [docker/extensions-sdk#209]
**Describe the bug**

When I start Docker Desktop and go on the __Installed__ of the Marketplace I can't see the unpublished extensions (those I manually installed).

This issue was reported on [#extensions in the Docker Community slack channel](https://dockercommunity.slack.com/archives/C03B18KTM27/p1660119145600079) by @daimor. I create this issue to give the community visibility on it.

The workaround is to close the dashboard (the UI) and reopen it. 

**Add the steps to reproduce**
Steps to reproduce the behaviour:

0. Open Docker Desktop
1. Go to the marketplace
2. Click on __Installed__
4. You don't see the extensions

**Describe the expected behaviour**

I expect to see the extensions

**Comment by benja-M-1** [comment]
Closing as it has been fixed in Docker Desktop 4.12

**Comment by gtardif** [comment]
This has been fixed in Desktop 4.12. Please feel free to re-open if you still experience issues with Docker Desktop 4.12 (released last week)

**Comment by daimor** [comment]
Just updated Docker Desktop, with already installed extension
The InterSystems extension is visible on the left side and works perfectly.
![image](https://user-images.githubusercontent.com/1212251/188455835-8a0195a5-df14-4bb4-b2e7-04014471fb0e.png)
The only way to restore it there is uninstall it with `docker extension rm` and install it back
![image](https://user-images.githubusercontent.com/1212251/188457077-a0656f2b-18d6-4bf2-bbc2-ffd4c61a2b6e.png)

**Comment by benja-M-1** [comment]
Reponing the issue as per @daimor's comment, we must investigate 😞

**Comment by benja-M-1** [comment]
I can't reproduce the issue and I discussed with @daimor who can't anymore. I close this issue for now, feel free to reopen it if it appears with Docker Desktop >= 4.12
