### ISSUE TITLE
Extension SDK debug ui issue throws Uncaught Error: This version of @docker/extension-api-client in debug mode

### ISSUE THREAD

**Issue by idevrlabs** [docker/extensions-sdk#211]
The built extension is working on Docker Desktop with no issues but not even showing on the browser @ http://localhost:3000 in debug mode instead throws the following exception

Using the instruction steps to debug posted @ [docker desktop extension document](https://docs.docker.com/desktop/extensions-sdk/build/test-debug/#hot-reloading-whilst-developing-the-ui)  

After npm start I see nothing in the UI in the browser developer console the following error is posted 

bootstrap:27         
       Uncaught Error: This version of @docker/extension-api-client is not supported by your version of Docker Desktop. Please upgrade to the latest version.
    at createDockerDesktopClient (index.js:5:1)
    at ./src/App.tsx (App.tsx:22:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.tsx (App.tsx:28:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
**Add the steps to reproduce**

**Output of `docker extension version`:**

```
Client Version: v0.2.8
Server API Version: 0.2.3
```

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### **Installed and referenced extension-api-client is** 

@docker/extension-api-client
TypeScript icon, indicating that this package has built-in type declarations
**### 0.2.3** • Public • Published 4 months ago

**Comment by idevrlabs** [comment]
This one too stuck in issue #210

**Comment by benja-M-1** [comment]
Hi @idevrlabs, thanks for opening this issue.

> The built extension is working on Docker Desktop with no issues but not even showing on the browser @ http://localhost:3000/ in debug mode instead throws the following exception

Docker Desktop extensions can't be used outside of Docker Desktop. This is why you see this error.

**Comment by idevrlabs** [comment]
> Hi @idevrlabs, thanks for opening this issue.
> 
> > The built extension is working on Docker Desktop with no issues but not even showing on the browser @ http://localhost:3000/ in debug mode instead throws the following exception
> 
> Docker Desktop extensions can't be used outside of Docker Desktop. This is why you see this error.

For hot-reloading in debug mode instructions are available at the following link and followed the steps mentioned at the below  link

https://docs.docker.com/desktop/extensions-sdk/build/test-debug/#hot-reloading-whilst-developing-the-ui

After npm start I see nothing in the UI in the browser developer console the following error is posted

bootstrap:27
Uncaught Error: This version of @docker/extension-api-client is not supported by your version of Docker Desktop. Please upgrade to the latest version.
at createDockerDesktopClient (index.js:5:1)
at ./src/App.tsx (App.tsx:22:1)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:62:1)
at ./src/index.tsx (App.tsx:28:1)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at startup:7:1
at startup:7:1

**Comment by benja-M-1** [comment]
> After npm start I see nothing in the UI in the browser developer console 

@idevrlabs, just to be sure, do you mean in Chrome? Or in the Docker Desktop dev tools?

**Comment by benja-M-1** [comment]
I guess `npm start`  opens the browser, we used to have this behaviour in the past. In `.env` in the client/ui folder add `BROWSER=none` to prevent this.

**Comment by idevrlabs** [comment]
> > After npm start I see nothing in the UI in the browser developer console
> 
> @idevrlabs, just to be sure, do you mean in Chrome? Or in the Docker Desktop dev tools?



> I guess `npm start` opens the browser, we used to have this behaviour in the past. In `.env` in the client/ui folder add `BROWSER=none` to prevent this. We have updated the `docker extension init` command that generates a new extension. We are in the process to update the samples as well.

Now we can't debug in chrome?  Then we need to remove hot-reloading instructions at this link. 

https://docs.docker.com/desktop/extensions-sdk/build/test-debug/#hot-reloading-whilst-developing-the-ui

I am referring to the following text @ the afore mentioned link
-------------------------------------------
Hot reloading whilst developing the UI
During UI development, it’s helpful to use hot reloading to test your changes without rebuilding your entire extension. To do this, you can configure Docker Desktop to load your UI from a development server, such as the one Create React App starts when invoked with yarn start.

Assuming your app runs on the default port, start your UI app and then run:

cd ui
npm start
This starts a development server that listens on port 3000.

You can now tell Docker Desktop to use this as the frontend source. In another terminal run:

$ docker extension dev ui-source <name-of-your-extensions> http://localhost:3000
----------------------------------------------------------------------------------------------

**Comment by idevrlabs** [comment]
> I guess `npm start` opens the browser, we used to have this behaviour in the past. In `.env` in the client/ui folder add `BROWSER=none` to prevent this. We have updated the `docker extension init` command that generates a new extension. We are in the process to update the samples as well.

This helps!

Thanks for your time.
