### ISSUE TITLE
Chaining shell commands does not work on Linux

### ISSUE THREAD

**Issue by aborroy** [docker/extensions-sdk#212]
**Describe the bug**
When executing the following code in Docker Desktop for Linux to stop all containers in a network...
```
export const stopContainers  = async () => {
    await ddClient.docker.cli.exec('stop', [
        '$(docker ps -qf "network=alfresco")'
    ])
}
```
... following error is obtained:
```
{"killed":false, "code":125, "signal":null, "cmd":"docker stop $(docker ps -qf \"network=alfresco\")","stdout":"","stderr":
"unknown shorthand flag: 'q' in -qf"}
```
The same code works as expected in Docker Desktop for Mac (Intel chip).

**Add the steps to reproduce**

1. Execute the code above in a Docker Extension

**Describe the expected behavior**
The expected behaviour is to get the same results from Docker Desktop Mac and Linux.

**Output of `docker extension version`:**

```
Client Version: v0.2.8
Server API Version: 0.2.3
```

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**
This issue raised when testing this Docker Extension with Docker Desktop for Linux:
https://github.com/AlfrescoLabs/alfresco-docker-extension/issues/1

**Comment by benja-M-1** [comment]
Hi @aborroy thanks you for reporting this! We are going to have a look asap. 

Have you tried to do it in two times? Something similar to 
```javascript
const containers = await ddClient.docker.cli.exec('ps', ['-qf', '"network=alfresco"']);
const stopedContainers = await ddClient.docker.cli.exec('stop', [...containers]);
```

I don't have a linux environment right now so I can't test, but I'll do soon. LMK if it works as a workaround.

**Comment by aborroy** [comment]
Thanks for your reply.

I can confirm following code works in Linux/Windows.

```
const containers = await ddClient.docker.cli.exec('ps', ['-qf', '"network=alfresco"'])
await ddClient.docker.cli.exec('stop', containers.stdout.split(/\r?\n|\r|\n/g))
```

Is there any guideline to write *ddClient* commands compatible with every OS?

**Comment by benja-M-1** [comment]
@aborroy thanks for confirming. 

> Is there any guideline to write ddClient commands compatible with every OS?
No there are not and there shouldn't be any differences. We need to investigate a bit I think. I can't tell right now why it does work. It is as if the command is not interpreted the same on Linux.

Under the hood, the SDK is simply executing the nodejs' `child_process:exec` function, similar to: `exec('docker stop $(docker ps -qf "network=alfresco")'`... 
BTW, if you run this on Linux, what does it output?
```javascript
const { exec } = require('node:child_process');
exec(''docker stop $(docker ps -qf "network=alfresco")'', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.error(`stderr: ${stderr}`);
});
```

**Comment by aborroy** [comment]
The output for the code above runs without issues in Linux.

```
stdout: 8aedb8a65f7d
4659feb30fcf

stderr:
```

Should that be related to some character escaping in the Docker command before passing it to `child_process`?

**Comment by benja-M-1** [comment]
Yes could be! Thank you for your help, we will dig deeper and let you know asap!

**Comment by gtardif** [comment]
At least for now, the `exec` API does not support chaining shell commands (neither ` cmd 1 arg 1 | cmd2 arg2` nor `cmd1 arg1 $(cmd2 arg2)`). We'll improve the documentation to make this more clear that you need to invoke commands one at a time and exchange arguments in the JS code.

**Comment by gtardif** [comment]
Docs have been updated to mention the fact that executing commands through the SDK does not allow to chain commands, see https://docs.docker.com/desktop/extensions-sdk/dev/api/docker/
