### ISSUE TITLE
Failed to load mp4/gif resources with net::ERR_FILE_NOT_FOUND 

### ISSUE THREAD

**Issue by sverdlov93** [docker/extensions-sdk#213]
**Describe the bug**
Getting 'Failed to load resource: net::ERR_FILE_NOT_FOUND' on mp4/gif files inside assets.
Works fine on the local browser.
Also, it works fine with gif/mp4 from web sources.

```
import mygif from '../assets/mygif.gif';
<img height="100px" width="100px" src={mygif} alt="" />
```
or 
```
import vid from '../assets/vid.mp4';
  <video  height="100%"  width="auto" muted autoPlay loop>
     <source src={vid} type="video/mp4" />
 </video>
```

```
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by benja-M-1** [comment]
Hi @sverdlov93 I managed to fix that in a reproduction case by adding a file named `global.d.ts` in the `ui/src` folder with the following content:

```typescript
declare module "*.gif" {
    const value: string;
    export default value;
}
```

Then, in my `App.tsx` I have the following:
```typescript
import React from 'react';
import mygif from './assets/giphy.gif';

export function App() {
  return (
      <img height="100px" width="100px" src={mygif} alt="" />
  );
}
```
And here is the result 👇 

<img width="1792" alt="Screenshot 2022-08-23 at 15 26 36" src="https://user-images.githubusercontent.com/212269/186170041-79f1a8ef-5d56-498d-b544-86c476163203.png">

I hope it helps :)

**Comment by sverdlov93** [comment]
Hi @benja-M-1, actually we have that file with the following code but still can't load mp4/gif.

```
declare module '*.mp4' {
  const value: string;
  export default value;
}

declare module "*.gif" {
  const value: string;
  export default value;
}

declare module '*.png' {
  const value: string;
  export default value;
}
```

**Comment by sverdlov93** [comment]
Anyway, if it works on your end it means that the issue is not on Docker Desktop side,  so the above issue can be closed.
Thanks!

**Comment by benja-M-1** [comment]
On my end the asset folder was under src. Is it the case for you?

**Comment by sverdlov93** [comment]
@benja-M-1 
Yes, it is.
I found out that the issue happens because of the React BrowserRouter. I am trying to find a solution to it.

**Comment by sverdlov93** [comment]
@benja-M-1 
Eventually, I solved it by adding <base> on index.html. 
```
<head>
    <base href="." />
    ...
</head>
```
