### ISSUE TITLE
Changing Licencing of Docker Desktop

### ISSUE THREAD

**Issue by potiuk** [docker/extensions-sdk#219]
**Is your feature request related to a problem? Please describe.**

This is in response to a request made by Docker team to Airflow project by  Amy Bass @amyb12345, product manager of Docker.

As explaned in https://github.com/apache/airflow/issues/26692#issuecomment-1258902593 - Apache Airflow is an Apache Software Foundation project, and the ASF core/foundational values are that software is released for free and the licensing terms of the software released cannot bind our users and expect then to pay under some circumstances. This is basic, core foundational value of the ASF and one that is basically non-negotiable (similarly as in case of Lightbend and Akka as described and extensively explained in https://issues.apache.org/jira/browse/LEGAL-619. Now - Docker reached out to us with the question and suggestion that Airlfow shoudl build Docker Desktop extension because the users demand it, and licencing model of the Docker Desktop is in stark contrast with the foundational core values of our projects and our organisation.

I assume this means that Docker is actually considering changing the licencing terms and is willing to make Docker Desktop completely free and not bind their users ? 

Many of our users either switched or consider switching to other solutions (https://podman.io/ mainly but also https://github.com/abiosoft/colima ) precisely because of the licensing model of Docker Desktop.

**Describe the solution you'd like**
If Docker Desktop team wants us to create an extension, I expect it to change the licence model to be in-line with freedom of choice for our users without being bound by expectations to pay money for using Docker Desktop.

**Describe alternatives you've considered**
* not writing the SDK
* providing guides to use Colima/Podman for Airflow

**Additional context**
This announcement : https://www.docker.com/blog/updating-product-subscriptions/

**Comment by gtardif** [comment]
As @amyb12345 mentioned, Docker Desktop does have a [free tier](https://www.docker.com/products/personal/) available non-commercial open source developers. 
Creating a Docker extension does not require any specific license change on your side. We understand that this may not meet your expectations, and you might not want to go any further with our proposal to build a Docker Extension for your product.
