### ISSUE TITLE
Maintaining extension state?

### ISSUE THREAD

**Issue by anderspitman** [docker/extensions-sdk#226]
First of all, thanks for building an excellent extension framework.

**Is your feature request related to a problem? Please describe.**
My extension uses `docker.cli.exec()` to run Docker commands. Commands such as pull are relatively long-running, and I don't want the user to be able to run multiple instances of the same command. I can disable the UI while they run, but I've noticed that if I navigate away from my extension and back too it, the UI is loaded fresh and enabled. The commands seem to run to completion, but I'm also not seeing toasts that I set up to notify that the command is done.

**Describe the solution you'd like**
It would be great if there was a place to store extension state across runs. That way on load I could check and see if a command is currently running. Though I don't believe this would solve the problem of the missing toasts.

**Describe alternatives you've considered**
Best I've thought of so far is running a backend service with the sole purpose of maintaining state. This feels like a very heavy handed approach, and I'm not even sure if this would work. I'm still new to Docker Desktop extension development and I'm not certain if the backend is stopped when you navigate away.

**Additional context**
N/A

Thanks,
//anders

**Comment by fbricon** [comment]
you can use localStorage, as we do in our OpenShift extension : https://github.com/redhat-developer/openshift-dd-ext/blob/main/client/src/hooks/useStorageState.ts

**Comment by anderspitman** [comment]
Thanks for the suggestion @fbricon. It looks like the JavaScript execution context gets torn down when I navigate away from the extension, so even though the command is completing, the JS after the command that resets my state is never called, so it thinks it's still running forever.

**Comment by felipecruz91** [comment]
Hi @anderspitman, I came across the same situation when developing the [Volumes Backup & Share extension](https://hub.docker.com/extensions/docker/volumes-backup-extension).

Exporting a volume is an operation that can take several minutes (similar to a docker pull) and I don't want the user to wait in the extension view until the operation completes. So what I did was to execute the long-running operation in a container and [keep the state in memory](https://github.com/docker/volumes-backup-extension/blob/main/vm/internal/handler/pull.go#L46-L48).

This way, every time the user leaves the extension and comes back, a request is made to the container to [read the state](https://github.com/docker/volumes-backup-extension/blob/main/ui/src/App.tsx#L336-L349).

**Comment by anderspitman** [comment]
Thanks @felipecruz91, this definitely gets me closer. If I understand the code correctly, you're using the Docker Golang library to perform Docker operations directly?

I'm still confused about how I can use that to pull an image into the Docker Desktop VM. If I run the command in the Extension VM Container, won't it not be visible to the DD VM? Or is there a way to pass the Docker socket to the Extension VM Container?

**Comment by felipecruz91** [comment]
> I'm still confused about how I can use that to pull an image into the Docker Desktop VM. If I run the command in the Extension VM Container, won't it not be visible to the DD VM? Or is there a way to pass the Docker socket to the Extension VM Container?

The [Docker Go SDK](https://docs.docker.com/engine/api/sdk/) initializes a Docker client to issue requests to the Docker engine. The image will be available/visible to the DD VM. Just make sure you mount the Docker socket as in [here](https://github.com/docker/volumes-backup-extension/blob/main/docker-compose.yaml#L8-L9).

**Comment by anderspitman** [comment]
@felipecruz91 sorry forgot to come back and respond to this. Your answer makes sense, thanks!
