### ISSUE TITLE
Write to a file in the VM

### ISSUE THREAD

**Issue by anderspitman** [docker/extensions-sdk#227]
**Is your feature request related to a problem? Please describe.**
My extension is running a tool that requires a config file. I need to be able to generate this file at runtime based on the user's input.

**Describe the solution you'd like**
Ideally I would like to be able to write this file entirely from the UI using JavaScript.

**Describe alternatives you've considered**
I tried something like the following:

```javascript
await ddClient.extension.vm?.cli?.exec('/bin/sh', [
  "-c",
  `echo '${configStr}' > /config.ini`,
]);
```

But the console logs indicate permission is denied.

Is there any writable location in the VM or another way to do this?

**Comment by anderspitman** [comment]
As a followup, I've confirmed that the extension Docker container is being run as root, and `/` is mounted rw, so I'm still at a loss as to what the problem is.

**Comment by anderspitman** [comment]
I got it to work by using a script to do the actual file creation. I would still be interested in understanding the root problem if anyone has ideas.

**Comment by felipecruz91** [comment]
Hi @anderspitman, thanks for reporting the issue. I can replicate it on my side and we'll be investigating it. Will let you know once we have a resolution.

**Comment by felipecruz91** [comment]
Hi @anderspitman, you have to wrap the echo command in double quotes:

```javascript
await ddClient.extension.vm?.cli?.exec('/bin/sh', [
    "-c",
    `"echo '${configStr}' > /config.ini"`,
]);
```

Once it is executed, if you `docker exec` into the extension container to inspect the filesystem, you will see the `/config.ini` file created:

![image](https://user-images.githubusercontent.com/15997951/208875835-c62dab58-4ff2-46ca-804d-e77b08e15584.png)


Feel free to re-open it if it doesn't work for you.

**Comment by anderspitman** [comment]
Thanks @felipecruz91, that did the trick. Also, I didn't realize you could access the terminal for extension containers. That's also very useful.
