### ISSUE TITLE
How to access ports of other containers from extension containers?

### ISSUE THREAD

**Issue by anderspitman** [docker/extensions-sdk#229]
**Is your feature request related to a problem? Please describe.**
My extension runs a reverse proxy (Caddy) which needs network access to the user's other running containers. However, it appears that extensions are not added to the default network bridge.

**Describe the solution you'd like**
A naive fix would be if extensions were automatically added to the default bridge. Open to other solutions though.

**Describe alternatives you've considered**
Best I've come up with so far is exposing container ports on the host, then using `host.docker.internal` inside my extension to access the exposed ports. However this has a few problems:

1. Extra non-default steps for my users to expose ports.
2. Potential security vulnerabilities because ports are exposed to other software running on the host.
3. I'm assuming there is significant performance overhead going out to the host and back into the Docker Desktop VM. Have not measured this yet.

**Comment by anderspitman** [comment]
I just performed some tests and confirmed that exposing services to the host and then accessing them from another container using `host.docker.internal` is much slower than going directly between containers using the default bridge, as expected.

**Comment by mikesir87** [comment]
Have you tried adding your proxy container to the networks of the other containers you're trying to connect to (or the other way around and attaching the containers to a proxy-specific network)? You run the risk of the containers you're trying to connect to being in custom networks (launched via Compose for example).

I was working on another extension with a similar need and that's how I ended up making it work.

**Comment by anderspitman** [comment]
Hi @mikesir87, thanks for the response and suggestion.

I'm trying to avoid managing a separate container outside my extension, although I could probably make that work. But I don't see a reason that my extension can't just run the proxy itself to keep things simple, if we can figure out a way around the networking.

One important constraint for my extension is I can't expect my users to be able to use the command line at all. Though one nice upside of this is that I shouldn't need to worry about them running containers using compose or other tools.

Is there a way to add containers to custom networks from the DD GUI? I've looked at couldn't find anything. If not, I suppose I could use my extension to add everything to a custom network by invoking Docker commands either from the JavaScript APIs or by passing the Docker socket to my extension container, right?

**Comment by mikesir87** [comment]
> I don't see a reason that my extension can't just run the proxy itself to keep things simple, if we can figure out a way around the networking.

That's exactly what I did for my extension. I basically owned the container and attached it to the various networks the user configured through the extension's GUI. 

> Is there a way to add containers to custom networks from the DD GUI?

DD doesn't have network functionality right now. So, would have to depend on your extension to supply that support.

> I suppose I could use my extension to add everything to a custom network by invoking Docker commands either from the JavaScript APIs or by passing the Docker socket to my extension container, right?

I'd definitely go the former if possible. The SDK will let you invoke Docker commands, so you can create networks, attach containers to networks, etc. 

The only thing I'm not sure about is how well a running process in a container may pick up the new network interface created for a new network attachment. Say, a web server. I imagine it might not bind to the new interface, so requests may not actually work. Worth an experiment. And may determine which route you go with where attachments occur.

**Comment by anderspitman** [comment]
Thanks again. I was able to successfully test managing custom networks from my extension. I think that will solve my problem.

Running processes not binding to the interface is a good point. I'll experiment with that before I close this, but I think worst case I should be able to restart containers that the user wants to proxy.

**Comment by anderspitman** [comment]
This has been working well. Interestingly, I haven't had any issues with needing to rebind interfaces. Thanks gain @mikesir87.

**Comment by mikesir87** [comment]
Hooray! Thanks for following up and letting me know it worked out @anderspitman! Looking forward to seeing your extension (if it's going to be publicly available). 😄
