### ISSUE TITLE
can´t install extensions on windows container

### ISSUE THREAD

**Issue by Julian-B90** [docker/extensions-sdk#234]
**Describe the bug**
When i switch to Windows Container. I can not install extensions and get this error:  

`Failed to install extension: Installation could not be completed due to: execution 'docker --context desktop-linux pull julianb90/tachometer:0.0.4': exit status 1: unable to resolve docker endpoint: context "desktop-linux" does not exist`

**Add the steps to reproduce**

1. Click to Docker Icon
2. Click "Switch to Winwos Container"
3. Go to "Browse Extensions"
4. And install an extension

**Output of `docker extension version`:**

```
Client Version: v0.2.19
Server API Version: 0.3.4
```

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:28:08 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:18:42 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Diagnostics ID
```
805B55F1-0706-477F-AF92-8FC72E7274F7/20230420061912
```

**Comment by felipecruz91** [comment]
Hi @Julian-B90, at the time of this writing, Docker Extensions are not currently supported on Windows containers, unfortunately. You'd need to switch back to Linux containers to make use of them.
