### ISSUE TITLE
Wrong version of Docker compose in Ubuntu package

### ISSUE THREAD

**Issue by alex-mashin** [docker/extensions-sdk#240]
Under Ubuntu 22.04, `apt install docker-compose-plugin` reports that it is of the newest version `2.21.0-1~ubuntu.23.04~lunar`. However, `docker compose version` reports `Docker Compose version v2.15.1`. The used repository is `https://download.docker.com/linux/ubuntu   lunar stable`.

**Comment by benja-M-1** [comment]
Hi @alex-mashin unless I am mistaken, I think you added this issue to the wrong repository. This one is about everything related to Docker extensions :)

**Comment by alex-mashin** [comment]
> Hi @alex-mashin unless I am mistaken, I think you added this issue to the wrong repository. This one is about everything related to Docker extensions :)

If `docker compose` is not a Docker extension, perhaps you know the right bug tracker? I will be grateful.

**Comment by benja-M-1** [comment]
I think this repo is more appropriate: https://github.com/docker/compose/issues

**Comment by alex-mashin** [comment]
> I think this repo is more appropriate: https://github.com/docker/compose/issues

Thank you.
