### ISSUE TITLE
Document OAuth flow

### ISSUE THREAD

**Issue by mikesir87** [docker/extensions-sdk#88]
In some extensions, it looks like an OAuth flow is possible to authenticate a user using the native web browser. I'd love to understand that flow, including the redirect URLs used to return the user back into the DD extension.

**Comment by gtardif** [comment]
The doc is now available at https://docs.docker.com/desktop/extensions-sdk/dev/oauth2-flow/
(and we'll likely improve this process by allowing to pass tokens in the `docker-desktop://xxx` URL in the future)
